### ISSUE TITLE
sourcemaps

### ISSUE THREAD

**Issue by dbox** [dbox/roots-bower#1]
Hey @hhsnopek -

Any idea why sourcemaps aren't working in this particular setup?

**Comment by dbox** [comment]
nm i think `out` in `css_pipeline` strips it out, for w/e reason...

**Comment by hhsnopek** [comment]
as long as you have: 

```
  stylus:
    sourcemap: true
```

you'll have sourcemaps, I cloned the repo down in it's current state and I do get sourcemaps this way
